---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: task name here
      ping:
    - name: Install telnet
      package: 
        name:
          - telnet
          - elinks
          - unzip
          - wget
        state: present