---
- name: R1soft Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: create a repo
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo

    - name: Install R1soft
      package:
        name: serverbackup-enterprise-agent
        state: latest
    
    - name: Power off iptables
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true

    - name: get key
      shell: r1soft-setup --get-key http://backup.enverguner.com

    - name: start r1soft agent
      systemd:
        name: sbm-agent
        state: restarted
        enabled: yes
